/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CategoriaController;
import Model.Categoria;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Helinks
 */
public class categoriaCrud extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(categoriaCrud.class.getName());
    public CategoriaController controller;

    /**
     * Creates new form categoriaCrud
     */
    public categoriaCrud() {
        initComponents();
        this.controller = new CategoriaController();
        estadoInicial();
        evento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void estadoInicial() {
        jScrollPane2.setVisible(false);
        resultadosBusqueda.setVisible(false);
        resultadosBusqueda.setModel(new DefaultListModel<>());
    }

    private void evento() {
        resultadosBusqueda.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                eventoClickEnLista(e);
            }
        });
    }

    public void eventoClickEnLista(MouseEvent e) {
        if (e.getClickCount() == 2) {
            int index = resultadosBusqueda.locationToIndex(e.getPoint());
            if (index >= 0) {
                Categoria categoriaSeleccionada =(Categoria) resultadosBusqueda.getModel().getElementAt(index);
                int id= categoriaSeleccionada.getId();
                String nombre=categoriaSeleccionada.getNombre();
                String[] opciones = {"Editar", "Borrar"};
                
                int respuesta = JOptionPane.showOptionDialog(this, "Que acción desea hacer con la categoria: " + nombre, nombre, JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, EXIT_ON_CLOSE);
                
                if (respuesta == 0) {
                    String respuestaEditar = JOptionPane.showInputDialog(this,"Editar categoria: ");
                    if(respuestaEditar == null){
                    return; }
                    this.controller.Edit(id, respuestaEditar);
                    JOptionPane.showMessageDialog(this, "Edición realizada con exito");
                    jButton2ActionPerformed(null);
                } else if (respuesta == 1) {
                    int respuestaBorrar = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea borrar esta categoria?");
                    if (respuestaBorrar == JOptionPane.YES_OPTION) {
                        this.controller.Delete(id);
                        JOptionPane.showMessageDialog(this, "Se ha borrado la categoria");
                        jButton2ActionPerformed(null);
                    }
                }
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        nombreCategoria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreCategoriaBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tituloResultado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadosBusqueda = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreCategoria.addActionListener(this::nombreCategoriaActionPerformed);

        jButton1.setText("Crear");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Crear categoria");

        jLabel2.setText("Nombre");

        jLabel3.setText("Buscar categoria");

        nombreCategoriaBuscar.addActionListener(this::nombreCategoriaBuscarActionPerformed);

        jButton2.setText("Buscar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel4.setText("Nombre de la categoria");

        jScrollPane2.setViewportView(resultadosBusqueda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreCategoria)
                                .addGap(53, 53, 53)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreCategoriaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tituloResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCategoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = nombreCategoria.getText();

        boolean nuevaCategoria = this.controller.Create(nombre);

        if (nuevaCategoria) {
            JOptionPane.showMessageDialog(this, "Se creo exitosamente la nueva categoria");
            nombreCategoria.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al crear la nueva categoria");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreCategoriaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCategoriaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCategoriaBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String busqueda = nombreCategoriaBuscar.getText().trim();

        List<Categoria> buscarCategoria = this.controller.Read(busqueda.toLowerCase());

        DefaultListModel<Categoria> modelo = (DefaultListModel<Categoria>) resultadosBusqueda.getModel();
        

        modelo.removeAllElements();

        if (busqueda.isEmpty()) {
            jScrollPane2.setVisible(false);
            resultadosBusqueda.setVisible(false);
            modelo.removeAllElements();
            tituloResultado.setText("Por favor llene el campo de busqueda");
            return;
        }
        if (buscarCategoria == null || buscarCategoria.isEmpty()) {
            jScrollPane2.setVisible(false);
            resultadosBusqueda.setVisible(false);
            modelo.removeAllElements();
            tituloResultado.setText("No se encontraron resultados");
            return;
        }

        tituloResultado.setText("Resultado");
        jScrollPane2.setVisible(true);
        resultadosBusqueda.setVisible(true);

        for (Categoria cat : buscarCategoria) {
            modelo.addElement(cat);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new categoriaCrud().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreCategoria;
    private javax.swing.JTextField nombreCategoriaBuscar;
    private javax.swing.JList<Model.Categoria> resultadosBusqueda;
    private javax.swing.JLabel tituloResultado;
    // End of variables declaration//GEN-END:variables
}
