/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Components.JPanelImageLogo;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Dilan
 */
public class HomeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeView.class.getName());

    public void configLogo(){
        JPanelImageLogo logoImagen = new JPanelImageLogo(logoJP,"/images/logo.png");
        logoJP.add(logoImagen).repaint();
        logoJP.setOpaque(false);
        logoJP.setBorder(null);
        logoJP.setBackground(new Color(0,0,0,0));
    }
    
    public void configHero(){
        JPanelImageLogo logoImagen = new JPanelImageLogo(heroImage,"/images/hero.png");
        heroImage.add(logoImagen).repaint();
        heroImage.setOpaque(false);
        heroImage.setBorder(null);
        heroImage.setBackground(new Color(0,0,0,0));
    }
    
    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        configLogo();
        configHero();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        heroImage = new javax.swing.JPanel();
        iniciarBtn = new javax.swing.JButton();
        logoJP = new javax.swing.JPanel();
        iniciarBtn2 = new javax.swing.JButton();
        registroBtn = new javax.swing.JButton();
        iniciarBtn3 = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        heroImage.setBackground(new java.awt.Color(2, 242, 242));

        iniciarBtn.setBackground(new java.awt.Color(201, 60, 98));
        iniciarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iniciarBtn.setForeground(new java.awt.Color(255, 255, 255));
        iniciarBtn.setText("Iniciar Sesion");
        iniciarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarBtn.setFocusPainted(false);
        iniciarBtn.setMargin(new java.awt.Insets(10, 20, 10, 20));
        iniciarBtn.addActionListener(this::iniciarBtnActionPerformed);

        javax.swing.GroupLayout logoJPLayout = new javax.swing.GroupLayout(logoJP);
        logoJP.setLayout(logoJPLayout);
        logoJPLayout.setHorizontalGroup(
            logoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        logoJPLayout.setVerticalGroup(
            logoJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        iniciarBtn2.setBackground(new java.awt.Color(254, 229, 230));
        iniciarBtn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iniciarBtn2.setForeground(new java.awt.Color(201, 60, 98));
        iniciarBtn2.setText("Carrito");
        iniciarBtn2.setBorderPainted(false);
        iniciarBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarBtn2.setFocusPainted(false);
        iniciarBtn2.setMargin(new java.awt.Insets(10, 20, 10, 20));
        iniciarBtn2.addActionListener(this::iniciarBtn2ActionPerformed);

        registroBtn.setBackground(new java.awt.Color(254, 229, 230));
        registroBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registroBtn.setForeground(new java.awt.Color(201, 60, 98));
        registroBtn.setText("Registrarse");
        registroBtn.setBorderPainted(false);
        registroBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registroBtn.setFocusPainted(false);
        registroBtn.setMargin(new java.awt.Insets(10, 20, 10, 20));
        registroBtn.addActionListener(this::registroBtnActionPerformed);

        iniciarBtn3.setBackground(new java.awt.Color(201, 60, 98));
        iniciarBtn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iniciarBtn3.setForeground(new java.awt.Color(201, 60, 98));
        iniciarBtn3.setText("Inicio");
        iniciarBtn3.setBorderPainted(false);
        iniciarBtn3.setContentAreaFilled(false);
        iniciarBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarBtn3.setFocusPainted(false);
        iniciarBtn3.setMargin(new java.awt.Insets(10, 20, 10, 20));
        iniciarBtn3.addActionListener(this::iniciarBtn3ActionPerformed);

        javax.swing.GroupLayout heroImageLayout = new javax.swing.GroupLayout(heroImage);
        heroImage.setLayout(heroImageLayout);
        heroImageLayout.setHorizontalGroup(
            heroImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heroImageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logoJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 612, Short.MAX_VALUE)
                .addComponent(iniciarBtn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarBtn)
                .addGap(18, 18, 18)
                .addComponent(registroBtn)
                .addGap(18, 18, 18))
        );
        heroImageLayout.setVerticalGroup(
            heroImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heroImageLayout.createSequentialGroup()
                .addGroup(heroImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(heroImageLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(heroImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iniciarBtn)
                            .addComponent(registroBtn)
                            .addComponent(iniciarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniciarBtn3)))
                    .addGroup(heroImageLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(logoJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(474, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heroImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(heroImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtnActionPerformed
        // TODO add your handling code here:
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_iniciarBtnActionPerformed

    private void registroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroBtnActionPerformed
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_registroBtnActionPerformed

    private void iniciarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarBtn2ActionPerformed

    private void iniciarBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel heroImage;
    private javax.swing.JButton iniciarBtn;
    private javax.swing.JButton iniciarBtn2;
    private javax.swing.JButton iniciarBtn3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel logoJP;
    private javax.swing.JButton registroBtn;
    // End of variables declaration//GEN-END:variables
}

